// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ExamApi.Models
{
    public partial class ExamDbContext : DbContext
    {
        public ExamDbContext()
        {
        }

        public ExamDbContext(DbContextOptions<ExamDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserLeaveBalance> UserLeaveBalance { get; set; }
        public virtual DbSet<UserLeaveHistory> UserLeaveHistory { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.UserName)
                    .HasName("PK_Users");

                entity.Property(e => e.UserName).HasMaxLength(50);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<UserLeaveBalance>(entity =>
            {
                entity.HasKey(e => e.UserName);

                entity.Property(e => e.UserName).HasMaxLength(50);

                entity.Property(e => e.Cl)
                    .HasColumnName("CL")
                    .HasDefaultValueSql("((6))");

                entity.Property(e => e.Pl)
                    .HasColumnName("PL")
                    .HasDefaultValueSql("((12))");

                entity.Property(e => e.Sl)
                    .HasColumnName("SL")
                    .HasDefaultValueSql("((6))");

                entity.HasOne(d => d.UserNameNavigation)
                    .WithOne(p => p.UserLeaveBalance)
                    .HasForeignKey<UserLeaveBalance>(d => d.UserName)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserLeaveBalance_User");
            });

            modelBuilder.Entity<UserLeaveHistory>(entity =>
            {
                entity.Property(e => e.FromDate).HasColumnType("date");

                entity.Property(e => e.LeaveType)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Reason)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.ToDate).HasColumnType("date");

                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.UserNameNavigation)
                    .WithMany(p => p.UserLeaveHistory)
                    .HasForeignKey(d => d.UserName)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserLeaveHistory_User1");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}