// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamApi.Models
{
    public partial class UserLeaveBalance
    {
        public string UserName { get; set; }
        public int? Pl { get; set; }
        public int? Cl { get; set; }
        public int? Sl { get; set; }

        public virtual User UserNameNavigation { get; set; }
    }
}