// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamApi.Models
{
    public partial class UserLeaveHistory
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public string Reason { get; set; }
        public int NumberOfDays { get; set; }
        public string LeaveType { get; set; }
        public bool? IsApproved { get; set; }

        public virtual User UserNameNavigation { get; set; }
    }
}